### PR TITLE
added styles for login & register

### PR DESCRIPTION
**Pull request by PRABHUDEESHWARAN**
I have added styles for login and register...no merge conflicts.

### CODE REVIEW

**Comment by ragul-engg** [comment]
The project already uses bootstrap as the CSS framework, why custom css though?, add the resultant image here for my reference.

**Comment by PRABHUDEESHWARAN** [comment]
> The project already uses bootstrap as the CSS framework, why custom css though?, add the resultant image here for my reference.

login
register

**Comment by ragul-engg** [comment]
You could have used the following classes in bootstrap to get the same result, can you try refactoring to use the bootstrap classes

* container
* d-flex
* flex-column
* justify-content-center
* align-items-center
* https://getbootstrap.com/docs/5.0/utilities/text/
* https://getbootstrap.com/docs/5.0/utilities/borders/

**Comment by PRABHUDEESHWARAN** [comment]
ogaiii try panren

**Pull request merged**
